# Generated by Django 5.1.5 on 2025-02-03 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_rename_damagerepairimage_repairimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damagerepairreport',
            name='images',
        ),
        migrations.AddField(
            model_name='repairimage',
            name='damage_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repair_images', to='communication.damagerepairreport'),
        ),
    ]
