# Generated by Django 5.1.5 on 2025-01-27 20:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roomie_property', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyCashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('electricity', 'Electricity'), ('garbage', 'Garbage'), ('internet', 'Internet'), ('heating', 'Heating')], max_length=50)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=50)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='roomie_property.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('electricity', 'Electricity'), ('garbage', 'Garbage'), ('internet', 'Internet'), ('heating', 'Heating')], default='category', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(default='Property payment', max_length=255)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=50)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_utility_payments', to='roomie_property.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=50)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('electricity', 'Electricity'), ('garbage', 'Garbage'), ('internet', 'Internet'), ('heating', 'Heating')], default='electricity', max_length=50)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_bills', to=settings.AUTH_USER_MODEL)),
                ('property_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_billings', to='cash_flow.propertypayments')),
            ],
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(default='Rent payment', max_length=255)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=50)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_payments', to='roomie_property.property')),
            ],
        ),
        migrations.CreateModel(
            name='TenantBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], max_length=50)),
                ('deadline', models.DateField()),
                ('rent_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_billings', to='cash_flow.rentpayment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('electricity', 'Electricity'), ('garbage', 'Garbage'), ('internet', 'Internet'), ('heating', 'Heating')], max_length=50)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=50)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('to_pay_order', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flow', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
