# Generated by Django 5.1.5 on 2025-01-26 16:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0002_propertycashflow'),
        ('roomie_property', '0003_propertytenantrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertycashflow',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertycashflow',
            name='category',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('garbage', 'Garbage'), ('internet', 'Internet'), ('heating', 'Heating')], max_length=50),
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(default='Rent payment', max_length=255)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=50)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_payments', to='roomie_property.property')),
            ],
        ),
    ]
