# Generated by Django 5.1.5 on 2025-01-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0003_propertypayments_help_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertypayments',
            name='help_text',
        ),
        migrations.AddField(
            model_name='propertybilling',
            name='help_text',
            field=models.DateField(blank=True, null=True),
        ),
    ]
