# Generated by Django 5.1.5 on 2025-01-28 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0004_remove_propertypayments_help_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertybilling',
            name='help_text',
        ),
        migrations.AddField(
            model_name='propertybilling',
            name='property_cash_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_cash_flows', to='cash_flow.propertycashflow'),
        ),
    ]
