# Generated by Django 5.1.5 on 2025-01-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0005_remove_propertybilling_help_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertybilling',
            name='property_cash_flow',
        ),
    ]
