# Generated by Django 5.1.5 on 2025-01-28 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0007_remove_propertybilling_property_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertybilling',
            name='property_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_billings', to='cash_flow.propertypayments'),
        ),
    ]
