# Generated by Django 5.1.5 on 2025-01-30 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0013_alter_usercashflow_property_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertybilling',
            name='property_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_billings', to='cash_flow.propertypayments'),
        ),
        migrations.AlterField(
            model_name='usercashflow',
            name='property_billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_cash_flows', to='cash_flow.propertybilling'),
        ),
    ]
