# Generated by Django 5.1.5 on 2025-01-30 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0014_alter_propertybilling_property_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercashflow',
            name='property_billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_cash_flows', to='cash_flow.propertybilling'),
        ),
    ]
