# Generated by Django 5.1.5 on 2025-01-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0018_alter_propertybilling_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantbilling',
            name='category',
            field=models.CharField(default='rent', max_length=50),
        ),
    ]
