# Generated by Django 5.1.5 on 2025-03-15 11:57

import cash_flow.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0019_tenantbilling_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentpayment',
            name='date',
            field=models.DateField(default=cash_flow.models.get_current_date),
        ),
    ]
