# Generated by Django 5.1.5 on 2025-01-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomie_user', '0002_customuser_email_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_address',
            field=models.BooleanField(default=False),
        ),
    ]
