# Generated by Django 5.1.5 on 2025-01-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomie_user', '0003_customuser_has_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='room_rating',
            new_name='user_rating_in_app',
        ),
    ]
