# Generated by Django 5.1.5 on 2025-01-25 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomie_property', '0002_alter_property_property_supervisor'),
        ('roomie_user', '0004_rename_room_rating_customuser_user_rating_in_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_addresses', to='roomie_property.property'),
        ),
    ]
