# Generated by Django 5.1.5 on 2025-01-25 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomie_user', '0007_addresshistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresshistory',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterField(
            model_name='addresshistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_history', to='roomie_user.customuser'),
        ),
    ]
