# Generated by Django 5.1.5 on 2025-02-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomie_property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
