# Generated by Django 5.1.5 on 2025-01-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomie_property', '0003_propertytenantrecords'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
