# Generated by Django 5.1.5 on 2025-02-02 14:00

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomie_property', '0003_alter_property_deposit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='main_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='main_image'),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('description', models.CharField(max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='roomie_property.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='additional_images',
            field=models.ManyToManyField(blank=True, related_name='properties', to='roomie_property.roomimage'),
        ),
    ]
