# Generated by Django 5.1.5 on 2025-02-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomie_property', '0004_property_main_image_roomimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='folio_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
