# Generated by Django 5.1.5 on 2025-02-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomie_property', '0005_property_folio_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='air_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
